$kind: http-request
name: productcategories get-all
url: "{{BE_URL}}/api/v1/productcategories/get-all"
method: POST
headers:
  Authorization: Bearer
    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjcwMDYwNWEtYjIwZC00NjAyLWE4ZDQtZmY4Y2ZjY2JkZWFkIiwidXNlcm5hbWUiOiJhZG1pbjEiLCJjdXN0b21lcl9pZCI6bnVsbCwiaWF0IjoxNzc2MTQwNzc0LCJleHAiOjE3NzY3NDU1NzR9.OMvKr2_xSXgUvUa7uwfzwskaLKhmeLPqzUDKPch9Lcs
  Content-Type: application/json
  refreshToken: "{{refreshToken}}"
body:
  type: json
  content: |-
    {
        "isactive": 1,
        "search": ""
    }
auth:
  type: bearer
  credentials:
    token: "{{accessToken}}"
order: 30000
